### ISSUE TITLE
How to compatible with Unicode character set project？

### ISSUE THREAD

**Issue by Ar-King** [hasherezade/libpeconv#4]
C2440	'default argument': cannot convert from 'LPWSTR' to 'const LPSTR'

peconv::ALIGNED_BUF load_resource_data(OUT size_t &out_size, const int res_id, const LPCSTR res_type = RT_RCDATA, HMODULE hInstance = nullptr);

I quoted the Lib file in the Unicode project and I would report it wrong. How should I be compatible with him

**Comment by hasherezade** [comment]
Hi! 
My first guess is that your problem occurred due to the fact, that I mistakenly used MAKEINTRESOURCE (implicit) rather than the explicit version: [MAKEINTRESOURCEA](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-makeintresourcea), which will not define types basing on external settings. This thing is fixed now, so please update to the latest commit, and let me know if it helped.

**Comment by Ar-King** [comment]
The problem seems to have been solved in half, and the RT_RCDATA in peconv:: ALIGNED_BUF load_resource_data (OUT size_t&out_size, const int res_id, const LPSTR res_type=RT_RCDATA, HMODULE hInstance=nullptr) needs to be deleted to be compiled and passed, because onst LPSTR res_type=RT_RCDATA=MAKEINESOURCE(10) = MAKEINTRESOURCEW, can you overload this function?

**Comment by hasherezade** [comment]
I am happy that it helped! Once you will be sure that no more fixes are needed, you can close this issue.
LibPeConv is published under [BSD-2 license](https://github.com/hasherezade/libpeconv/blob/master/LICENSE) so you can use it freely in your projects. You can just add a link to [libpeconv repo](https://github.com/hasherezade/libpeconv/) in your readme, and mentioned that it was used - and that's all.
Thanks!

**Comment by Ar-King** [comment]
Thank you very math!
