### ISSUE TITLE
error LNK2001

### ISSUE THREAD

**Issue by Voskrese** [hasherezade/libpeconv#8]
msvc ver 2017 x64 dynamic  \\\ DEBUG

`user32.lib(USER32.dll) : error LNK2001: unresolved external symbol __delayLoadHelper2`

> set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
> set(DELAYLOAD_FLAG "/DELAYLOAD:\"user32.dll\"" )
> 
> set (srcs
> 	main.cpp
> )
> 
> set (hdrs
> )
> 
> add_executable ( ${PROJECT_NAME} ${hdrs} ${srcs})
> set_property(TARGET ${PROJECT_NAME} APPEND_STRING PROPERTY LINK_FLAGS " ${DELAYLOAD_FLAG}")

https://docs.microsoft.com/ru-ru/cpp/build/reference/specifying-dlls-to-delay-load?view=vs-2019

`cl t.cpp user32.lib delayimp.lib  /link /DELAYLOAD:user32.dll`

`add `std lib `delayimp`.lib ?
```

add_executable ( ${PROJECT_NAME} ${hdrs} ${srcs})
target_link_libraries(${PROJECT_NAME} delayimp.lib)
set_property(TARGET ${PROJECT_NAME} APPEND_STRING PROPERTY LINK_FLAGS " ${DELAYLOAD_FLAG}")
```

**Comment by hasherezade** [comment]
It is weird, I cannot reproduce your problem. I also use Visual Studio 2017 x64. I tried to compile it in a Debug configuration and had no issues. 

![compile_success](https://user-images.githubusercontent.com/3115348/59507062-2d790080-8eaa-11e9-84d1-5a4da6dc190e.png)

Also on [AppVeyor it compiles cleanly and passes all the tests](https://ci.appveyor.com/project/hasherezade/libpeconv), so I don't think my CMake file is wrong.
You said: "add std lib delayimp.lib ?" - but there is no such lib in the project, in the example that you linked the name `delayimp.lib` was used just as a dummy name, not that literally this lib is needed. 

Please make sure that this problem is not caused by some misconfiguration on your side.

And as a temporary workaround, to make the library work, you can just disable building tests (this exe with delayload imports is just a part of the test cases, not of the libpeconv itself). Tests can be disabled just by unmarking the option `PECONV_BUILD_TESTING`:

![disable_tests](https://user-images.githubusercontent.com/3115348/59507195-9f514a00-8eaa-11e9-9d8a-80c0b6fd5cbc.png)

**Comment by Voskrese** [comment]
CMAKE_GENERATOR `Ninja`

**Comment by Voskrese** [comment]
Oops ... accidentally closed))

**Comment by hasherezade** [comment]
Please check if this update helped you. I cannot really check because for me it worked before too.

**Comment by Voskrese** [comment]
Apparently you need to add to each test and maybe I'm mistaken with the parameters of cmake

**Comment by hasherezade** [comment]
But this is the only exe in the project that uses delayload imports...

**Comment by Voskrese** [comment]
ok, I'll get to the working machine, check it out

**Comment by hasherezade** [comment]
ok, let me know...

**Comment by Voskrese** [comment]
ok
> tests\tests.exe
> 
> TESTS DEPLOYED!
> 
> Supply the test id!

install block in CMakeLists.txt?

```
install(TARGETS ${targets}
        RUNTIME DESTINATION bin
        LIBRARY DESTINATION lib
        ARCHIVE DESTINATION lib
)
```

**Comment by hasherezade** [comment]
@Voskrese - I am glad that it worked now. I can add those install blocks too, it is not a problem. But please make a separate issue for this, because it is a different topic than those linking problems.
